baseurl         = "/"
theme           = "minion"
languageCode    = "en-us"
title           = "Golang Training"
canonifyurls    = true

[params]
  googleAnalytics = ""
  name            = "Iván Jaimes"
  description     = "Primer sesión de entrenamiento con Go"
  custom_css      = ["custom.css"]
